services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Maispace\MaiAssets\:
        resource: '../Classes/*'
        exclude:
            - '../Classes/Event/*'
            - '../Classes/EventListener/*'

    Maispace\MaiAssets\EventListener\AboveFoldObserverListener:
        tags:
            - name: event.listener
              identifier: 'mai-assets/above-fold-observer'

    Maispace\MaiAssets\EventListener\SvgSpriteInjectionListener:
        tags:
            - name: event.listener
              identifier: 'mai-assets/svg-sprite-injection'

    Maispace\MaiAssets\EventListener\HtmlMinificationListener:
        tags:
            - name: event.listener
              identifier: 'mai-assets/html-minification'
              after: 'mai-assets/svg-sprite-injection'

    Maispace\MaiAssets\Collector\SvgSpriteCollector:
        shared: true

    Maispace\MaiAssets\Collector\FontPreloadCollector:
        shared: true

    Maispace\MaiAssets\Cache\AboveFoldCacheService:
        shared: true

    Maispace\MaiAssets\Command\WarmupCommand:
        tags:
            - name: console.command
              command: 'maispace:assets:warmup'
